name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Aftman
        uses: ok-nick/setup-aftman@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Wally packages
        run: sh scripts/install-packages.sh

      - name: Validate single-place and multi-place projects
        run: sh scripts/validate.sh
